Repository SlightlyLargeNC/scripts, pull requests merged in 2024-09, with the labels that each got.

#1 Merge dev to main
  randomstuff/gbs2.7z
  randomstuff/stereo.7z
  randomstuff/why microsoft.7z
Labels: addition

#2 Commit README.md change to dev
  README.md
Labels: repo

#3 Merge dev to main
  randomstuff/pink.cfgc
Labels: addition

#6 Update dependencies.md to include requirements for biting
  dependencies.md
Labels: addition

#7 add an other BITE
  randomstuff/BITTEN.txt
Labels: addition

#8 Merge main into dev
  dependencies.md
  randomstuff/BITTEN.txt
Labels: repo

#13 Merge main into dev
  randomstuff/BITTEN.txt
Labels: repo

#14 Merge main into dev
  BASHin' -1000 beeper.sh
  BASHin' -1000 noaafc.sh
  dependencies.md
Labels: repo

#17 Merge script change into main
  BASHin' -1000 beeper.sh
Labels: change, repo

#23 Merge main into dev
  dependencies.md
Labels: repo

#25 Cleanup Attempt 2
  BITTEN.txt
  RANDOM BEEPS.sh
  README.md
  beeper piano.sh
  dependencies.md
  furmodules/17 roll empty.fur
  furmodules/Bees.fur
  furmodules/L4MP-axel_f.mod.fur
  furmodules/L4MP-saltwater_bridge.mod.fur
  furmodules/PWM on OPL2.fur
  furmodules/XLMP-fatsteven.xm.fur
  furmodules/XLMP-nestiglader.xm.fur
  furmodules/XLMP-tm_getgroove.xm.fur
  furmodules/ambience2-sid3.fur
  furmodules/bwrrooowwwSLPOINK.fur
  furmodules/chords.fur
  furmodules/cool thing.fur
  furmodules/dtmtsid3.fur
  furmodules/everfuckloopbackphase.fur
  furmodules/layoutshowcasesong.fur
  furmodules/linux pc speaker test 200hz.fur
  furmodules/m me whennne tghhhghhrhe.fur
  furmodules/the world's most elaborate Empty cover.fur
  furmodules/this_is_me.mod sid3 cover.fur
  furmodules/unknown beeper.fur
  furmodules/unnamedaviosoundsongsid3cover.fur
  furmodules/ventsong.fur
  furmodules/x1-010-cover-of-t.fur
Labels: removal, cleanup, requires review

#26 update dev branch
  BITTEN.txt
  RANDOM BEEPS.sh
  README.md
  beeper piano.sh
  dependencies.md
  furmodules/17 roll empty.fur
  furmodules/Bees.fur
  furmodules/L4MP-axel_f.mod.fur
  furmodules/L4MP-saltwater_bridge.mod.fur
  furmodules/PWM on OPL2.fur
  furmodules/XLMP-fatsteven.xm.fur
  furmodules/XLMP-nestiglader.xm.fur
  furmodules/XLMP-tm_getgroove.xm.fur
  furmodules/ambience2-sid3.fur
  furmodules/bwrrooowwwSLPOINK.fur
  furmodules/chords.fur
  furmodules/cool thing.fur
  furmodules/dtmtsid3.fur
  furmodules/everfuckloopbackphase.fur
  furmodules/layoutshowcasesong.fur
  furmodules/linux pc speaker test 200hz.fur
  furmodules/m me whennne tghhhghhrhe.fur
  furmodules/the world's most elaborate Empty cover.fur
  furmodules/this_is_me.mod sid3 cover.fur
  furmodules/unknown beeper.fur
  furmodules/unnamedaviosoundsongsid3cover.fur
  furmodules/ventsong.fur
  furmodules/x1-010-cover-of-t.fur
Labels: repo

#28 shit accidentally edited the dev branch instead of main
  README.md
Labels: repo

#29 Update BASHin' -1000 beeper.sh
  BASHin' -1000 beeper.sh
Labels: change
